# __Hands-on with TensorFlow: Part A__
 this demo, let's see how TensorFlow works and build a deep neural network model using the MNIST dataset.

## Step 1: Import TensorFlow

- Import TensorFlow and check its version


In [26]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


## Step 2: Load the MNIST Dataset

- Load the MNIST dataset and normalize the input data by dividing the train and test sets by 255



In [27]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

__Observation:__
- The dataset has been downloaded.

## Step 3: Create the Model

- Create a Sequential model with Flatten, Dense, and Dropout layers


In [28]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Step 4: Get Predictions from the Model

- Get the predictions from the model using the train data for one column, as the optimizer is not yet applied


In [29]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.3633845 ,  0.63742155,  0.72694665,  0.70626116, -0.84114337,
        -0.0098706 ,  0.79921377, -0.05048534,  0.06423756, -0.386028  ]],
      dtype=float32)

__Observation:__
- An array of predicted values is displayed.

## Step 5: Apply Softmax Activation to the Predictions

- Apply softmax activation to the predictions and print the output in terms of probabilities


In [30]:
tf.nn.softmax(predictions).numpy()

array([[0.10446642, 0.1374009 , 0.15026914, 0.14719267, 0.03132254,
        0.07192405, 0.16153067, 0.06906141, 0.07745669, 0.04937545]],
      dtype=float32)

__Observation:__
- The predicted values in terms of probabilities are displayed as an array.

## Step 6: Define the Loss Function

- Let's create a loss function for the model.
- Next, let's define the SparseCategoricalCrossentropy loss function.


In [31]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [32]:
loss_fn(y_train[:1], predictions).numpy()

2.6321445

__Observation:__
- Here,the value is 2.061.

## Step 7: Compile the Model

- Now, compile the model with the Adam optimizer, the loss function, and the accuracy metric

In [33]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

__Observation:__
- Here, we have used an optimizer as Adam, loss as a loss function, and metrics as accuracy.

## Step 8: Train the Model

- Fit the model using the training data for 5 epochs


In [34]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3024 - accuracy: 0.9123
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1460 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1098 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0887 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0761 - accuracy: 0.9766


__Observations:__
- The model fits the data.
- Here, we can see that the accuracy is increased by different epochs.

## Step 9: Evaluate the Model

- Evaluate the model using the testing data and print the results


In [35]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0668 - accuracy: 0.9782 - 396ms/epoch - 1ms/step


[0.0668352022767067, 0.9782000184059143]

__Observation:__

- The accuracy score is 0.9779, and the loss is 0.071.

## Step 10: Create a Probability Model

- Create a probability model by adding the Softmax layer to the existing model



In [36]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

- And, get the predictions using the test data

In [37]:
probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[1.9782617e-06, 1.9197207e-08, 7.8528938e-05, 1.6191219e-04,
        1.3626786e-11, 1.4135667e-06, 4.4371760e-13, 9.9975222e-01,
        2.7696291e-07, 3.5809292e-06],
       [1.5188199e-06, 1.7499551e-03, 9.9792731e-01, 3.1914003e-04,
        1.0835503e-14, 1.3473141e-06, 5.1437763e-07, 4.7613974e-12,
        2.1119800e-07, 3.3589512e-14],
       [2.2343370e-07, 9.9883312e-01, 1.5714944e-04, 1.0794544e-06,
        3.4083387e-05, 8.9012826e-07, 5.9101712e-06, 9.0264116e-04,
        6.3375475e-05, 1.5456823e-06]], dtype=float32)>

__Observation:__
- Here, we have the probabilities for the first three observations and different classes.