#Dimensionality Reduction and Matrix Factorization
Let us understand how to implement matrix factorization in collaborative filtering.

*   Dimensionality reduction is the process of reducing a matrix's dimension to a lesser value than it currently has.
*   A group of cooperative filtering methods used in recommender systems is called matrix factorization.





## Step 1: Import Required Libraries


*   Import package NumPy





In [1]:
import numpy as np

## Step 2: Define Matrix Factorization Function
- We have R, P, Q, K, and steps = 5000, along with alpha and beta.
*   Transpose Q and use the for loop in range. The range will be converted to len(R). 
*   If R, i, and j are greater than zero, take the dot product of P of i and Q of j for k in the range to subtract that
*   If beta is subtracted from the Q of k and j, add alpha multiplied by eij
*   If e is less than 0.001, break and return P, Q, and T





In [2]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if e < 0.001:
            break
    return P, Q.T

\mathbf{R} \approx \mathbf{P} \times \mathbf{Q}^T = \hat{\mathbf{R}}

## Step 3: Define the Input Matrix and Parameters

- Define the input matrix R
- Apply matrix factorization
- Define the dimensions N, M, and K
- Initialize the P and Q matrices with random values

In [3]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]

R = np.array(R)

N = len(R) #rows
M = len(R[0]) #columns

K = 2   #reduction factor

In [ ]:
#Create an initial random matrix
P = np.random.rand(N,K)
Q = np.random.rand(M,K)

## Step 4: Perform Matrix Factorization and Calculate the Approximated Matrix

- Now let us call the `matrix_factorization` function with the input matrix and parameters.
- Calculate the approximated matrix nR

In [9]:
nP, nQ = matrix_factorization(R, P, Q, K)
nP


array([[2.32998606, 0.27325226],
       [1.86638419, 0.30876628],
       [0.52104305, 2.21368192],
       [0.50679017, 1.76723066],
       [0.59842477, 1.76508609]])

In [11]:
nQ

array([[ 2.14190046, -0.04963525],
       [ 1.26287764,  0.14768706],
       [ 1.44001887,  2.33392917],
       [ 0.1716097 ,  2.20473331]])

## Expand the matrix back to see how good is the approximation

In [10]:
nR = np.dot(nP, nQ.T)
nR

array([[4.97703525, 2.98284312, 3.99297532, 1.00229657],
       [3.98228345, 2.40261564, 3.40826706, 1.00103692],
       [1.00614569, 0.9849458 , 5.91688863, 4.96999429],
       [0.99777715, 0.90101107, 4.8543786 , 3.98324241],
       [1.19415578, 1.01641763, 4.98132887, 3.99423958]])

nR is very good approximation to R.
We reduced the dimension and approximate the original values back.

__Observation:__
- In this matrix factorization, we have been able to update the values from the input matrix R to the above values.